server.port=8080

spring.application.name=resource-booking-system

# Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/real_estate
spring.datasource.username=postgres
spring.datasource.password=ganesh
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
app.jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

# SpringDoc OpenAPI (Swagger UI)
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.operationsSorter=method
